apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-app
  ports:
    - name: http
      port: 80          # LoadBalancer port
      targetPort: 8080  # Container port
